export const TMPL_PUNCH_V2 = {
  size: {
    height: 1125,
    width: 1125,
    quality: 0.85,
  },
  background:
    'http://img.ps.laiye.com/checkinAlbum_20190917050919_Au753g458J.jpg',
  globalStyle: {
    base: {
      fillStyle: '#333',
      strokeStyle: '#FFF',
      fontSize: 28,
      // font: '500 28px "PingFang SC"',
      textBaseline: 'top',
    },
    text: {
      shadowBlur: 5,
      shadowColor: 'rgba(0, 0, 0, 0.4)',
      shadowOffsetX: 0,
      shadowOffsetY: 2,
      fillStyle: '#FFF',
    },
    line: {
      shadowBlur: 5,
      shadowColor: 'rgba(0, 0, 0, 0.4)',
      shadowOffsetX: 0,
      shadowOffsetY: 2,
      fillStyle: '#FFF',
    },
    image: {
      shadowBlur: 5,
      shadowColor: 'rgba(0, 0, 0, 0.4)',
      shadowOffsetX: 0,
      shadowOffsetY: 2,
    },
  },
  components: [
    {
      shape: {
        type: 'circle',
      },
      height: 132,
      imageUrl:
        'http://img.laiye.com/ajNVdqHZLLCjOXLicIVrSh3OtofBx98A33VZRIxRTZ3pbM0WmuEREicrGONaBvmVKnx6aibQ3cjhr2heCCKjcB4nuEqBT0o74nrQ1AARIzvwzU.jpg',
      name: 'avatar',
      type: 'image',
      width: 132,
      x: 32,
      y: 52,
    },
    {
      height: 146,
      imageUrl:
        'http://img.laiye.com/G0gmxRbVb4GgMwAk5B4VKeX6a0mfB5HXtjdv9YMZkj03D0A.png',
      name: 'qrcode',
      type: 'image',
      width: 146,
      x: 944,
      y: 944,
    },
    {
      fillStyle: '#FFF',
      content: '坚持早起',
      // fontWeight: 'bold',
      name: 'continueTip',
      size: 37,
      type: 'text',
      x: 30,
      y: 265,
    },
    {
      textAlign: 'left',
      fillStyle: '#FFF',
      content: '22',
      fontWeight: 'bold',
      name: 'continuousTotal',
      size: 100,
      type: 'severalDays',
      x: 34,
      y: 302,
      affiliate: {
        fillStyle: '#FFF',
        content: '天',
        fontWeight: 'bold',
        name: 'continueUnit',
        size: 44,
        type: 'continuousText',
        x: 50.5,
        y: 357,
      },
    },
    {
      fillStyle: '#FFF',
      content: '今日打卡',
      // fontWeight: 'bold',
      name: 'today',
      size: 37,
      type: 'text',
      x: 30,
      y: 452,
    },
    {
      fillStyle: '#FFF',
      content: '11:40',
      fontWeight: 'bold',
      name: 'punchTime',
      size: 100,
      type: 'text',
      x: 30,
      y: 490,
    },
    {
      textAlign: 'right',
      fillStyle: '#FFF',
      content: '25',
      // fontWeight: 'light',
      limit: 120,
      name: 'day',
      size: 70,
      type: 'text',
      x: 967.5,
      y: 45.5,
    },
    {
      textAlign: 'right',
      fillStyle: '#FFF',
      content: '2019.09',
      // fontWeight: 'bold',
      limit: 120,
      name: 'yearMonth',
      size: 50,
      type: 'text',
      x: 967.5,
      y: 120,
    },
    {
      textAlign: 'left',
      fillStyle: '#FFF',
      content: '7993984人正在参与',
      // fontWeight: 'bold',
      name: 'join',
      size: 36,
      type: 'text',
      x: 34,
      y: 675,
    },
    {
      textAlign: 'left',
      fillStyle: '#FFF',
      content: '比1万人起的早',
      // fontWeight: 'bold',
      name: 'earlierThan',
      size: 37,
      type: 'text',
      x: 34,
      y: 720,
    },
    {
      textAlign: 'right',
      fillStyle: '#FFF',
      strokeStyle: '#FFF',
      content: '不管多么崎岖不平',
      fontWeight: 'bold',
      limit: 615,
      lineHeight: 45,
      name: 'beautifulWordsPart1',
      size: 38,
      type: 'text',
      x: 300,
      y: 940,
    },
    {
      textAlign: 'right',
      fillStyle: '#FFF',
      strokeStyle: '#FFF',
      content: '也比站在原地更接近幸福',
      fontWeight: 'bold',
      limit: 615,
      lineHeight: 45,
      name: 'beautifulWordsPart2',
      size: 38,
      type: 'text',
      x: 300,
      y: 988,
    },
    {
      fillStyle: '#FFF',
      strokeStyle: '#FFF',
      content: '扫码和我互道早安',
      name: 'welcomeMessage',
      size: 36,
      type: 'text',
      limit: 615,
      x: 300,
      y: 1045,
    },
    {
      fillStyle: '#FFF',
      strokeStyle: '#FFF',
      lineWidth: 3,
      name: 'splitLine',
      type: 'line',
      x1: 34,
      x2: 396,
      y1: 645,
      y2: 645,
    },
  ],
}
export const TMPL_PUNCH_NIGHT_V2 = {
  size: {
    height: 1125,
    width: 1125,
    quality: 0.85,
  },
  background:
    'http://img.ps.laiye.com/checkinAlbum_20190917050919_Au753g458J.jpg',
  globalStyle: {
    base: {
      fillStyle: '#333',
      strokeStyle: '#FFF',
      fontSize: 28,
      // font: '500 28px "PingFang SC"',
      textBaseline: 'top',
    },
    text: {
      shadowBlur: 5,
      shadowColor: 'rgba(0, 0, 0, 0.4)',
      shadowOffsetX: 0,
      shadowOffsetY: 2,
      fillStyle: '#FFF',
    },
    line: {
      shadowBlur: 5,
      shadowColor: 'rgba(0, 0, 0, 0.4)',
      shadowOffsetX: 0,
      shadowOffsetY: 2,
      fillStyle: '#FFF',
    },
    image: {
      shadowBlur: 5,
      shadowColor: 'rgba(0, 0, 0, 0.4)',
      shadowOffsetX: 0,
      shadowOffsetY: 2,
    },
  },
  components: [
    {
      shape: {
        type: 'circle',
      },
      height: 132,
      imageUrl:
        'http://img.laiye.com/ajNVdqHZLLCjOXLicIVrSh3OtofBx98A33VZRIxRTZ3pbM0WmuEREicrGONaBvmVKnx6aibQ3cjhr2heCCKjcB4nuEqBT0o74nrQ1AARIzvwzU.jpg',
      name: 'avatar',
      type: 'image',
      width: 132,
      x: 32,
      y: 52,
    },
    {
      height: 146,
      imageUrl:
        'http://img.laiye.com/G0gmxRbVb4GgMwAk5B4VKeX6a0mfB5HXtjdv9YMZkj03D0A.png',
      name: 'qrcode',
      type: 'image',
      width: 146,
      x: 944,
      y: 944,
    },
    {
      fillStyle: '#FFF',
      content: '坚持早睡',
      // fontWeight: 'bold',
      name: 'continueTip',
      size: 37,
      type: 'text',
      x: 30,
      y: 265,
    },
    {
      textAlign: 'left',
      fillStyle: '#FFF',
      content: '22',
      fontWeight: 'bold',
      name: 'continuousTotal',
      size: 100,
      type: 'severalDays',
      x: 34,
      y: 302,
      affiliate: {
        fillStyle: '#FFF',
        content: '天',
        fontWeight: 'bold',
        name: 'continueUnit',
        size: 44,
        type: 'continuousText',
        x: 50.5,
        y: 357,
      },
    },
    {
      fillStyle: '#FFF',
      content: '今日入睡',
      // fontWeight: 'bold',
      name: 'today',
      size: 37,
      type: 'text',
      x: 30,
      y: 452,
    },
    {
      fillStyle: '#FFF',
      content: '11:40',
      fontWeight: 'bold',
      name: 'punchTime',
      size: 100,
      type: 'text',
      x: 30,
      y: 490,
    },
    {
      textAlign: 'right',
      fillStyle: '#FFF',
      content: '25',
      // fontWeight: 'light',
      limit: 120,
      name: 'day',
      size: 70,
      type: 'text',
      x: 967.5,
      y: 45.5,
    },
    {
      textAlign: 'right',
      fillStyle: '#FFF',
      content: '2019.09',
      // fontWeight: 'bold',
      limit: 120,
      name: 'yearMonth',
      size: 50,
      type: 'text',
      x: 967.5,
      y: 120,
    },
    {
      textAlign: 'left',
      fillStyle: '#FFF',
      content: '7993984人正在参与',
      // fontWeight: 'bold',
      name: 'join',
      size: 36,
      type: 'text',
      x: 34,
      y: 675,
    },
    {
      textAlign: 'left',
      fillStyle: '#FFF',
      content: '比1万人睡的早',
      // fontWeight: 'bold',
      name: 'earlierThan',
      size: 37,
      type: 'text',
      x: 34,
      y: 720,
    },
    {
      textAlign: 'right',
      fillStyle: '#FFF',
      strokeStyle: '#FFF',
      content: '不管多么崎岖不平',
      fontWeight: 'bold',
      limit: 615,
      lineHeight: 45,
      name: 'beautifulWordsPart1',
      size: 38,
      type: 'text',
      x: 300,
      y: 940,
    },
    {
      textAlign: 'right',
      fillStyle: '#FFF',
      strokeStyle: '#FFF',
      content: '也比站在原地更接近幸福',
      fontWeight: 'bold',
      limit: 615,
      lineHeight: 45,
      name: 'beautifulWordsPart2',
      size: 38,
      type: 'text',
      x: 300,
      y: 988,
    },
    {
      fillStyle: '#FFF',
      strokeStyle: '#FFF',
      content: '扫码和我互道晚安',
      name: 'welcomeMessage',
      size: 36,
      type: 'text',
      limit: 615,
      x: 300,
      y: 1045,
    },
    {
      fillStyle: '#FFF',
      strokeStyle: '#FFF',
      lineWidth: 3,
      name: 'splitLine',
      type: 'line',
      x1: 34,
      x2: 396,
      y1: 645,
      y2: 645,
    },
  ],
}
export const TMPL_PUNCH_OLD = {
  size: {
    width: 1004,
    height: 969,
    quality: 0.85,
  },
  background:
    'http://img.ps.laiye.com/checkinAlbum_20190917050919_Au753g458J.jpg',
  globalStyle: {
    base: {
      fillStyle: '#333',
      strokeStyle: '#FFF',
      fontSize: 28,
      // font: '500 28px "PingFang SC"',
      textBaseline: 'top',
    },
    // text: {
    //   shadowBlur: 5,
    //   shadowColor: 'rgba(0, 0, 0, 0.4)',
    //   shadowOffsetX: 0,
    //   shadowOffsetY: 2,
    //   fillStyle: '#FFF',
    // },
    // line: {
    //   shadowBlur: 5,
    //   shadowColor: 'rgba(0, 0, 0, 0.4)',
    //   shadowOffsetX: 0,
    //   shadowOffsetY: 2,
    //   fillStyle: '#FFF',
    // },
    // image: {
    //   shadowBlur: 5,
    //   shadowColor: 'rgba(0, 0, 0, 0.4)',
    //   shadowOffsetX: 0,
    //   shadowOffsetY: 2,
    // },
  },
  components: [
    {
      type: 'shape',
      gradient: {
        x1: 502,
        y1: 550,
        x2: 502,
        y2: 969,
        color: {
          startPosition: 0,
          startColor: 'rgba(255,255,255,0)',
          endPosition: 1,
          endColor: 'rgba(255,255,255,1)',
        },
      },
      x: 0,
      y: 550,
      width: 1004,
      height: 469,
    },
    {
      type: 'shape',
      gradient: {
        x1: 765,
        y1: 0,
        x2: 765,
        y2: 153,
        color: {
          startPosition: 0,
          startColor: 'rgba(255,255,255,1)',
          endPosition: 1,
          endColor: 'rgba(255,255,255,0)',
        },
      },
      x: 765,
      y: 0,
      width: 174,
      height: 153,
    },
    {
      type: 'shape',
      fillStyle: 'rgba(255,255,255,0.8)',
      x: 66,
      y: 318,
      width: 873,
      height: 273,
      radius: 45,
    },
    {
      shape: {
        type: 'circle',
      },
      height: 168,
      imageUrl:
        'http://img.laiye.com/ajNVdqHZLLCjOXLicIVrSh3OtofBx98A33VZRIxRTZ3pbM0WmuEREicrGONaBvmVKnx6aibQ3cjhr2heCCKjcB4nuEqBT0o74nrQ1AARIzvwzU.jpg',
      name: 'avatar',
      type: 'image',
      width: 168,
      x: 123,
      y: 371,
    },
    {
      height: 130,
      imageUrl:
        'http://img.laiye.com/G0gmxRbVb4GgMwAk5B4VKeX6a0mfB5HXtjdv9YMZkj03D0A.png',
      name: 'qrcode',
      type: 'image',
      width: 130,
      x: 809,
      y: 728,
    },
    {
      fillStyle: '#606167',
      content: '你已经坚持早起',
      name: 'continueTip',
      size: 30,
      type: 'text',
      x: 560,
      y: 425,
    },
    {
      textAlign: 'left',
      fillStyle: '#000000',
      content: '22',
      fontWeight: 'bold',
      name: 'continuousTotal',
      size: 53,
      type: 'severalDays',
      x: 783,
      y: 405,
      affiliate: {
        fillStyle: '#606167',
        content: '天',
        name: 'continueUnit',
        size: 30,
        type: 'continuousText',
        x: 790,
        y: 425,
      },
    },
    {
      fillStyle: '#000000',
      content: '11:40',
      fontWeight: 'bold',
      name: 'punchTime',
      size: 75,
      type: 'text',
      x: 332,
      y: 380,
    },
    {
      fillStyle: '#1E0E01',
      content: '25',
      name: 'day',
      size: 59,
      type: 'text',
      x: 819,
      y: 60,
    },
    {
      fillStyle: '#1E0E01',
      content: '七月',
      name: 'month',
      size: 30,
      type: 'text',
      x: 819,
      y: 35,
    },
    {
      fillStyle: '#616268',
      content: '7993984人正在参与',
      name: 'join',
      size: 30,
      type: 'text',
      x: 333,
      y: 495,
    },
    {
      textAlign: 'left',
      fillStyle: '#000000',
      content: '比1万人起的早',
      fontWeight: 'bold',
      name: 'earlierThan',
      size: 30,
      type: 'text',
      x: 685,
      y: 495,
    },
    {
      textAlign: 'right',
      fillStyle: '#2C2D2F',
      content: '绳锯木断 水滴石穿',
      fontWeight: 'bold',
      limit: 615,
      lineHeight: 45,
      name: 'beautifulWordsPart',
      size: 34,
      type: 'text',
      x: 170,
      y: 775,
    },
    {
      fillStyle: '#9D9EA7',
      content: '扫码和我互道早安',
      name: 'welcomeMessage',
      size: 26,
      type: 'text',
      limit: 615,
      x: 170,
      y: 825,
    },
  ],
}
export const TMPL_PUNCH_V1 = {
  size: {
    height: 1125,
    width: 1125,
    quality: 0.85,
  },
  background:
    'http://img.ps.laiye.com/checkinAlbum_20190917050919_Au753g458J.jpg',
  globalStyle: {
    base: {
      fillStyle: '#333',
      strokeStyle: '#FFF',
      fontSize: 28,
      textBaseline: 'top',
    },
    text: {
      shadowBlur: 5,
      shadowColor: 'rgba(0, 0, 0, 0.4)',
      shadowOffsetX: 0,
      shadowOffsetY: 2,
      fillStyle: '#FFF',
      textAlign: 'left',
    },
    line: {
      shadowBlur: 5,
      shadowColor: 'rgba(0, 0, 0, 0.4)',
      shadowOffsetX: 0,
      shadowOffsetY: 2,
      fillStyle: '#FFF',
    },
    image: {
      shadowBlur: 5,
      shadowColor: 'rgba(0, 0, 0, 0.4)',
      shadowOffsetX: 0,
      shadowOffsetY: 2,
    },
  },
  components: [
    {
      shape: {
        type: 'circle',
      },
      height: 150,
      imageUrl:
        'http://img.laiye.com/ajNVdqHZLLCjOXLicIVrSh3OtofBx98A33VZRIxRTZ3pbM0WmuEREicrGONaBvmVKnx6aibQ3cjhr2heCCKjcB4nuEqBT0o74nrQ1AARIzvwzU.jpg',
      name: 'avatar',
      type: 'image',
      width: 150,
      x: 48,
      y: 48,
    },
    {
      height: 150,
      imageUrl:
        'http://img.laiye.com/G0gmxRbVb4GgMwAk5B4VKeX6a0mfB5HXtjdv9YMZkj03D0A.png',
      name: 'qrcode',
      type: 'image',
      width: 150,
      x: 930,
      y: 930,
    },
    {
      fillStyle: '#FFF',
      content: '坚持早起',
      fontWeight: 'bold',
      name: 'continueTip',
      size: 39,
      type: 'text',
      font: 'bold 39px "PingFang SC"',
      x: 45,
      y: 277.5,
    },
    {
      fillStyle: '#FFF',
      content: 1,
      fontWeight: 'bold',
      name: 'continuousTotal',
      size: 99,
      type: 'text',
      x: 45,
      y: 336,
    },
    {
      fillStyle: '#FFF',
      content: '天',
      fontWeight: 'bold',
      name: 'continueUnit',
      size: 36,
      type: 'text',
      x: 112.5,
      y: 384,
    },
    {
      fillStyle: '#FFF',
      content: '今日早起',
      fontWeight: 'bold',
      name: 'today',
      size: 39,
      type: 'text',
      x: 45,
      y: 472.5,
    },
    {
      fillStyle: '#FFF',
      content: '11:40',
      fontWeight: 'bold',
      name: 'punchTime',
      size: 99,
      type: 'text',
      x: 45,
      y: 528,
    },
    {
      textAlign: 'right',
      fillStyle: '#FFF',
      content: '25',
      fontWeight: '',
      limit: 120,
      name: 'day',
      size: 75,
      type: 'text',
      x: 967.5,
      y: 25.5,
    },
    {
      textAlign: 'right',
      fillStyle: '#FFF',
      content: '2019.09',
      fontWeight: 'bold',
      limit: 120,
      name: 'yearMonth',
      size: 30,
      type: 'text',
      x: 967.5,
      y: 120,
    },
    {
      fillStyle: '#FFF',
      content: '7993984人正在参与',
      fontWeight: 'bold',
      name: 'join',
      size: 36,
      type: 'text',
      x: 45,
      y: 694.5,
    },
    {
      fillStyle: '#FFF',
      content: '比1万人起的早',
      fontWeight: 'bold',
      name: 'earlierThan',
      size: 36,
      type: 'text',
      x: 45,
      y: 745.5,
    },
    {
      textAlign: 'right',
      fillStyle: '#FFF',
      strokeStyle: '#FFF',
      content: '我们不缺方向',
      fontWeight: 'bold',
      limit: 615,
      lineHeight: 45,
      name: 'beautifulWordsPart1',
      size: 39,
      type: 'text',
      x: 270,
      y: 921,
    },
    {
      textAlign: 'right',
      fillStyle: '#FFF',
      content: '缺的是一往无前的决心和魄力',
      fontWeight: 'bold',
      limit: 615,
      lineHeight: 45,
      name: 'beautifulWordsPart2',
      size: 39,
      type: 'text',
      x: 270,
      y: 966,
    },
    {
      fillStyle: '#FFF',
      strokeStyle: '#FFF',
      content: '扫码和我互道早安',
      name: 'welcomeMessage',
      size: 39,
      type: 'text',
      x: 570,
      y: 1035,
    },
    {
      fillStyle: '#FFF',
      strokeStyle: '#FFF',
      lineWidth: 1.5,
      name: 'splitLine',
      type: 'line',
      x1: 45,
      x2: 405,
      y1: 679,
      y2: 679,
    },
  ],
}

export const TMPL_PUNCH_V3 = {
  size: {
    height: 1147,
    width: 1125,
    quality: 0.85,
  },
  background:
    'http://schedule-1253442168.file.myqcloud.com/punch_background/20531571039755_.pic_hd.jpg',
  globalStyle: {
    base: {
      fillStyle: '#fff',
      strokeStyle: '#FFF',
      fontSize: 34,
      textBaseline: 'top',
    },
    text: {
      shadowBlur: 5,
      shadowColor: 'rgba(0, 0, 0, 0.4)',
      shadowOffsetX: 0,
      shadowOffsetY: 2,
      fillStyle: '#FFF',
      // textAlign: 'left',
    },
    line: {
      shadowBlur: 5,
      shadowColor: 'rgba(0, 0, 0, 0.4)',
      shadowOffsetX: 0,
      shadowOffsetY: 2,
      fillStyle: '#FFF',
    },
    image: {
      shadowBlur: 5,
      shadowColor: 'rgba(0, 0, 0, 0.4)',
      shadowOffsetX: 0,
      shadowOffsetY: 2,
    },
  },
  components: [
    {
      shape: {
        type: 'circle',
      },
      height: 123,
      imageUrl:
        'http://img.laiye.com/ajNVdqHZLLCjOXLicIVrSh3OtofBx98A33VZRIxRTZ3pbM0WmuEREicrGONaBvmVKnx6aibQ3cjhr2heCCKjcB4nuEqBT0o74nrQ1AARIzvwzU.jpg',
      name: 'avatar',
      type: 'image',
      width: 123,
      x: 30,
      y: 71,
    },
    {
      height: 150,
      imageUrl:
        'http://img.laiye.com/G0gmxRbVb4GgMwAk5B4VKeX6a0mfB5HXtjdv9YMZkj03D0A.png',
      name: 'qrcode',
      type: 'image',
      width: 150,
      x: 949,
      y: 954,
    },
    {
      fillStyle: '#FFF',
      content: '七月',
      name: 'month',
      size: 35,
      type: 'text',
      x: 170,
      y: 78,
    },
    {
      fillStyle: '#FFF',
      content: '16',
      name: 'day',
      size: 60,
      type: 'text',
      x: 170,
      y: 130,
    },
    {
      fillStyle: '#FFF',
      content: '坚持早起',
      name: 'continueTip',
      type: 'text',
      font: '500 40px "PingFang SC"',
      x: 30,
      y: 296,
    },
    {
      fillStyle: '#FFF',
      content: '1天',
      fontWeight: 'bold',
      name: 'continuousTotal',
      size: 100,
      type: 'text',
      x: 30,
      y: 354,
    },
    {
      fillStyle: '#FFF',
      content: '今日打卡',
      name: 'today',
      size: 40,
      type: 'text',
      x: 30,
      y: 508,
    },
    {
      fillStyle: '#FFF',
      content: '11:40',
      fontWeight: 'bold',
      name: 'punchTime',
      size: 100,
      type: 'text',
      x: 30,
      y: 584,
    },

    {
      fillStyle: '#FFF',
      content: '7993984人正在参与',
      fontWeight: 'bold',
      name: 'join',
      size: 34,
      type: 'text',
      x: 30,
      y: 1000,
    },
    {
      fillStyle: '#FFF',
      content: '比1万人起的早',
      fontWeight: 'bold',
      name: 'earlierThan',
      size: 34,
      type: 'text',
      x: 30,
      y: 1040,
    },
    {
      textAlign: 'right',
      fillStyle: '#FFF',
      strokeStyle: '#FFF',
      content: '不管多么崎岖不平',
      fontWeight: 'bold',
      limit: 615,
      lineHeight: 45,
      name: 'beautifulWordsPart1',
      size: 38,
      type: 'text',
      x: 290,
      y: 960,
    },
    {
      textAlign: 'right',
      fillStyle: '#FFF',
      strokeStyle: '#FFF',
      content: '也比站在原地更接近幸福',
      fontWeight: 'bold',
      limit: 615,
      lineHeight: 45,
      name: 'beautifulWordsPart2',
      size: 38,
      type: 'text',
      x: 290,
      y: 1008,
    },
    {
      fillStyle: '#FFF',
      strokeStyle: '#FFF',
      content: '扫码和我互道早安',
      name: 'welcomeMessage',
      size: 30,
      type: 'text',
      limit: 615,
      x: 290,
      y: 1065,
    },
    {
      fillStyle: '#FFF',
      strokeStyle: '#FFF',
      lineWidth: 3.5,
      name: 'tipLine',
      type: 'tipLine',
      tipWidth: 6,
      tipHeight: 6,
      tipMargin: 10,
      x1: 32,
      x2: 32,
      y1: 1091,
      y2: 1103,
      repeat: 3,
    },
    {
      fillStyle: '#FFF',
      strokeStyle: '#FFF',
      lineWidth: 1.5,
      name: 'splitLine',
      lineDash: [3, 3], //param1 点宽 param2 点间距
      type: 'line',
      x1: 32,
      x2: 32,
      y1: 683,
      y2: 907,
    },
  ],
}

export const TMPL_ACHIEVEMENT_SOCIAL = {
  size: {
    height: 1128,
    width: 1005,
    quality: 0.85,
  },
  globalStyle: {
    base: {
      fillStyle: '#333',
      strokeStyle: '#FFF',
      fontSize: 28,
      textBaseline: 'top',
      textAlign: 'left',
    },
  },
  background:
    'http://schedule-1253442168.file.myqcloud.com/background/social_achievement.png',
  components: [
    {
      height: 446,
      imageUrl: 'http://cdn.mitty.work/%E7%BB%84%2071.png',
      name: 'imageUrl',
      type: 'image',
      width: 446,
      x: 281,
      y: 116,
    },
    {
      shape: {
        type: 'circle',
      },
      borderRadius: 36, // ??
      height: 105,
      imageUrl:
        'http://img.laiye.com/ajNVdqHZLLCjOXLicIVrSh3OtofBx98A33VZRIxRTZ3pbM0WmuEREicrGONaBvmVKnx6aibQ3cjhr2heCCKjcB4nuEqBT0o74nrQ1AARIzvwzU.jpg',
      name: 'avatar',
      type: 'image',
      width: 105,
      x: 89,
      y: 881,
    },
    {
      height: 159,
      imageUrl:
        'http://img.laiye.com/G0gmxRbVb4GgMwAk5B4VKeX6a0mfB5HXtjdv9YMZkj03D0A.png',
      name: 'qrcode',
      type: 'image',
      width: 159,
      x: 749,
      y: 848,
    },
    {
      color: '#2C2C2C',
      content: '坚持早起3天',
      name: 'title',
      size: 49,
      type: 'text',
      x: 1005 / 2, //canvas的一般宽度
      textAlign: 'center',
      y: 605,
      fontWeight: '500',
    },
    {
      color: '#8D8D8D',
      content: '邀请完朋友后说的一句文案',
      name: 'achievedCopy',
      size: 38,
      type: 'text',
      x: 1005 / 2,
      y: 672,
      textAlign: 'center',
    },
    {
      color: '#BCBEC1',
      content: '2019年10月8日获得',
      name: 'date',
      size: 34,
      type: 'text',
      x: 216,
      y: 890,
      textAlign: 'left',
      textBaseline: 'top',
    },
    {
      color: '#BCBEC1',
      content: '已超过18990人',
      name: 'earlierThan',
      size: 34,
      type: 'text',
      x: 216,
      y: 930,
      textAlign: 'left',
      textBaseline: 'top',
    },
  ],
}
export const TMPL_ACHIEVEMENT_SOLAR_TERMS = TMPL_ACHIEVEMENT_SOCIAL
export const TMPL_ACHIEVEMENT_CONTINUOUS = TMPL_ACHIEVEMENT_SOCIAL

export const ALL_TEMPLATES = {
  TMPL_PUNCH_V1,
  TMPL_PUNCH_V2,
  TMPL_PUNCH_NIGHT_V2,
  TMPL_PUNCH_V3,
  TMPL_ACHIEVEMENT_CONTINUOUS,
  TMPL_ACHIEVEMENT_SOCIAL,
  TMPL_ACHIEVEMENT_SOLAR_TERMS,
  TMPL_PUNCH_OLD,
}
